### ISSUE TITLE
Put local setup instructions in the Readme

### ISSUE THREAD

**Issue by agsdot** [ismith/elevator_alerts#16]
Hi Ian,

Can you put instructions on the readme for people to run and develop elevator_alerts on their local computer? I just heard about your project last week at the Berkeley SCI group at the Ed Roberts Campus.

It's been a while since I've used sinatra, and having guidelines on getting all the working parts together for this project would be great. 

Thanks!

**Comment by ismith** [comment]
Sure!

**Comment by agsdot** [comment]
Thanks!

**Comment by ismith** [comment]
Hey @agsdot - take a look, let me know what you think.

**Comment by agsdot** [comment]
Thanks @ismith , I'll be looking at this over the next couple days and provide some feedback. Thanks!
